# Goal - I have to Lint, Build, Test the code for Frontend & Backend
# then Push the images to DockerHub 
name: CI

on:
  push:
    branches: [adavanced]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: actions/checkout@v7
      
      # Step 2: Provision the specified Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm' # Automates npm dependency caching to speed up workflows

    # Step 3: Clean install dependencies using package-lock.json
      - name: Install dependencies
        run: npm ci

      - name: run linter
        run: npm run lint

    # Step 5: Run your test suite
      - name: Run tests
        run: npm test



  #backend:



  #deploy: